# Para subir os serviços execute `docker compose up -d`
# Para desligar execute `docker compose down`
services:
  redis:
    image: redis:7.4-alpine
    container_name: delivery-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-deliverytech}" , "--save", "60", "1000"]
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-deliverytech}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-deliverytech}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  redis_data:
    driver: local
