apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-api
  labels:
    app: delivery-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-api
  template:
    metadata:
      labels:
        app: delivery-api
    spec:
      containers:
        - name: delivery-api
          image: ghcr.io/rrublez/delivery-api-rrubleske:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: delivery-api-config
            - secretRef:
                name: delivery-api-db-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts: []
      imagePullSecrets:
        - name: ghcr-secret
      restartPolicy: Always
