apiVersion: v1
kind: Secret
metadata:
  name: delivery-api-db-secret
  labels:
    app: delivery-api
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: delivery_user
  SPRING_DATASOURCE_PASSWORD: change-me
